# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.18.2
kotlin_version=2.4.20
fabric_kotlin_version=1.14.1+kotlin.2.4.20

# Mod Properties
mod_version=1.1.4-26.1.2
maven_group=com.dulkirfabric
archives_base_name=DulkirMod-Fabric

# Dependencies
fabric_version=0.155.2+26.1.2

# ModMenu
modMenu_version=18.0.2

# Cloth Config
clothConfig_version=26.1.154

# Orbit
orbit_version=0.2.3
